/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg9typical_cafe;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author wolfie
 */
public class Form_DashboardAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_DashboardAdmin
     */
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    public Form_DashboardAdmin() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        executeSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jL_jumlahMenu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jL_jumlahPegawai = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jL_jumlahTransaksi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jL_Perbandingan = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jL_jumlahPendapatan = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jL_totalPendapatan = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1280, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jumlah Menu");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jL_jumlahMenu.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jL_jumlahMenu.setForeground(new java.awt.Color(255, 255, 255));
        jL_jumlahMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_jumlahMenu.setText("-");
        jPanel1.add(jL_jumlahMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 330, 180));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah Pegawai");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jL_jumlahPegawai.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jL_jumlahPegawai.setForeground(new java.awt.Color(255, 255, 255));
        jL_jumlahPegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_jumlahPegawai.setText("-");
        jPanel2.add(jL_jumlahPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 330, 180));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Transaksi");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Pesanan 30 hari terakhir");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 30));

        jL_jumlahTransaksi.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jL_jumlahTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jL_jumlahTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_jumlahTransaksi.setText("-");
        jPanel3.add(jL_jumlahTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 330, 180));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DASHBOARD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 270, 70));

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Perbandingan Pendapatan 30 Hari lalu");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 330, 50));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jL_Perbandingan.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jL_Perbandingan.setForeground(new java.awt.Color(255, 255, 255));
        jL_Perbandingan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Perbandingan.setText("-");
        jPanel8.add(jL_Perbandingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 130));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 330, 180));

        jPanel13.setBackground(new java.awt.Color(255, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 102, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Pendapatan");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 50));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jPanel15.setBackground(new java.awt.Color(255, 102, 102));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Pendapatan 30 hari terakhir");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 30));

        jL_jumlahPendapatan.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jL_jumlahPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        jL_jumlahPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_jumlahPendapatan.setText("-");
        jPanel13.add(jL_jumlahPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 100));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 180));

        jPanel11.setBackground(new java.awt.Color(255, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Pendapatan");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 50));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jL_totalPendapatan.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jL_totalPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        jL_totalPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_totalPendapatan.setText("-");
        jPanel11.add(jL_totalPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 130));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, 180));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1280, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void executeSQL(){
        JumlahPegawai();
        JumlahMenu();
        JumlahTransaksi();
        JumlahPendapatan();
        TotalPendapatan();
        PerbandinganPendapatan();
    }
    
    private void PerbandinganPendapatan(){
        int duaBulan = 0;
        
        int bulanBelakangan = Integer.valueOf(jL_jumlahPendapatan.getText());
        
        try {
            sql = "SELECT SUM(total_harga) AS pendapatan FROM transaksi WHERE tanggal >= (CURDATE() - INTERVAL 2 MONTH) AND tanggal <= (CURDATE() - INTERVAL 1 MONTH)";
            rs = stat.executeQuery(sql);
            if(rs.next()){
               duaBulan = Integer.valueOf(rs.getString("pendapatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
        double selisih = bulanBelakangan - duaBulan;
        double a =  selisih / bulanBelakangan;
        double b = a * 100;
        String hasil = String.valueOf(b);
        jL_Perbandingan.setText(hasil.substring(0,5) +" %");
    }
    
    private void JumlahPendapatan(){
        try {
            sql = "SELECT SUM(total_harga) AS pendapatan FROM transaksi WHERE tanggal >= (CURDATE() - INTERVAL 1 MONTH)";
            rs = stat.executeQuery(sql);
            if(rs.next()){
               jL_jumlahPendapatan.setText(rs.getString("pendapatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void TotalPendapatan(){
        try {
            sql = "SELECT SUM(total_harga) AS pendapatan FROM transaksi";
            rs = stat.executeQuery(sql);
            if(rs.next()){
               jL_totalPendapatan.setText(rs.getString("pendapatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void JumlahMenu(){
        try {
            sql = "SELECT COUNT(*) AS jumlahMenu FROM menu";
            rs = stat.executeQuery(sql);
            if(rs.next()){
               jL_jumlahMenu.setText(rs.getString("jumlahMenu"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void JumlahTransaksi(){
        try {
            sql = "SELECT COUNT(*) AS jumlahTransaksi FROM transaksi WHERE tanggal >= (CURDATE() - INTERVAL 1 MONTH)";
            rs = stat.executeQuery(sql);
            if(rs.next()){
               jL_jumlahTransaksi.setText(rs.getString("jumlahTransaksi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void JumlahPegawai(){
        try {
            sql = "SELECT COUNT(*) AS jumlahPegawai FROM user";
            rs = stat.executeQuery(sql);
            if(rs.next()){
               jL_jumlahPegawai.setText(rs.getString("jumlahPegawai"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_Perbandingan;
    private javax.swing.JLabel jL_jumlahMenu;
    private javax.swing.JLabel jL_jumlahPegawai;
    private javax.swing.JLabel jL_jumlahPendapatan;
    private javax.swing.JLabel jL_jumlahTransaksi;
    private javax.swing.JLabel jL_totalPendapatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
