/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg9typical_cafe;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wolfie
 */
public class Form_AddUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_AddUser
     */
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public Form_AddUser() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        loadTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_user = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTF_nama = new javax.swing.JTextField();
        jPF_password = new javax.swing.JPasswordField();
        jTF_username = new javax.swing.JTextField();
        jCB_type = new javax.swing.JComboBox<>();
        jB_refresh = new javax.swing.JButton();
        jB_create = new javax.swing.JButton();
        jB_edit = new javax.swing.JButton();
        jB_delete = new javax.swing.JButton();
        jTF_search = new javax.swing.JTextField();
        jB_search = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("FORM TAMBAH USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 410, 60));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText(":");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 20, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, -1));

        jT_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Username", "Type"
            }
        ));
        jT_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_user);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1260, 190));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 20, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 20, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText(":");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 20, -1));
        getContentPane().add(jTF_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 440, 40));
        getContentPane().add(jPF_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 440, 40));
        getContentPane().add(jTF_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 440, 40));

        jCB_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir", " " }));
        jCB_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_typeActionPerformed(evt);
            }
        });
        getContentPane().add(jCB_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 140, -1));

        jB_refresh.setText("Refresh");
        jB_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(jB_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 140, 40));

        jB_create.setText("Create");
        jB_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_createActionPerformed(evt);
            }
        });
        getContentPane().add(jB_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 140, 40));

        jB_edit.setText("Edit");
        jB_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editActionPerformed(evt);
            }
        });
        getContentPane().add(jB_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 140, 40));

        jB_delete.setText("Delete");
        jB_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jB_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 140, 40));
        getContentPane().add(jTF_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 450, 40));

        jB_search.setText("Search");
        jB_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jB_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_typeActionPerformed

    private void jB_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_createActionPerformed
        // TODO add your handling code here:
        create();
    }//GEN-LAST:event_jB_createActionPerformed

    private void jT_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_userMouseClicked
        // TODO add your handling code here:
        jTF_nama.setText(String.valueOf(jT_user.getValueAt(jT_user.getSelectedRow(),0)));
        jTF_username.setText(String.valueOf( jT_user.getValueAt(jT_user.getSelectedRow(),1)));
        jPF_password.setText(String.valueOf( jT_user.getValueAt(jT_user.getSelectedRow(),2)));
        jCB_type.setSelectedItem(String.valueOf(jT_user.getValueAt(jT_user.getSelectedRow(),3)));
    }//GEN-LAST:event_jT_userMouseClicked

    private void jB_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editActionPerformed
        editData();
    }//GEN-LAST:event_jB_editActionPerformed

    private void jB_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_deleteActionPerformed
        delete();
    }//GEN-LAST:event_jB_deleteActionPerformed

    private void jB_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_refreshActionPerformed
        loadTabel();
    }//GEN-LAST:event_jB_refreshActionPerformed

    private void jB_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_searchActionPerformed
        String cariData = jTF_search.getText();
        if(cariData.isEmpty()){
            JOptionPane.showMessageDialog(this, "Isikan data pencarian");
        }else{
            searchData(cariData);
        }
        clear();
        
        
    }//GEN-LAST:event_jB_searchActionPerformed
    
    private void editData(){
        try {
           if( !jTF_nama.getText().isEmpty() && !jTF_username.getText().isEmpty() && !jPF_password.getText().isEmpty()){

                sql = "UPDATE user SET nama='"+ jTF_nama.getText() + "', username='" + jTF_username.getText() +
                        "', password='"+ jPF_password.getText()+"', type='"+ jCB_type.getSelectedItem().toString()
                        +"' WHERE username ='" + String.valueOf(jT_user.getValueAt(jT_user.getSelectedRow(),1))+"'";
                stat.executeUpdate(sql);
                
                JOptionPane.showMessageDialog(this, "Data Berhasil Diedit");
            }else{
                JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error edit data");
        }
        loadTabel();
        clear();
    }
    
    private void searchData(String cariData){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nama");
        tb.addColumn("Username");
        tb.addColumn("Password");
        tb.addColumn("Type");

        jT_user.setModel(tb);
        jT_user.getColumnModel().getColumn(2).setWidth(0);
        jT_user.getColumnModel().getColumn(2).setMinWidth(0);
        jT_user.getColumnModel().getColumn(2).setMaxWidth(0);     
       try {
            sql = "SELECT * FROM user WHERE nama LIKE '%" + cariData + "%' OR type LIKE '%" + cariData + "%'";
            rs = stat.executeQuery(sql);
            
            while(rs.next()){
               tb.addRow(new Object[] {
                   rs.getString("nama"),
                   rs.getString("username"),
                   rs.getString("password"),
                   rs.getString("type"),
               });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
          
        clear();
    }
    private void loadTabel() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nama");
        tb.addColumn("Username");
        tb.addColumn("Password");
        tb.addColumn("Type");

        jT_user.setModel(tb);
        jT_user.getColumnModel().getColumn(2).setWidth(0);
        jT_user.getColumnModel().getColumn(2).setMinWidth(0);
        jT_user.getColumnModel().getColumn(2).setMaxWidth(0);     
       try {
            sql = "SELECT * FROM user";
            rs = stat.executeQuery(sql);
            
            while(rs.next()){
               tb.addRow(new Object[] {
                   rs.getString("nama"),
                   rs.getString("username"),
                   rs.getString("password"),
                   rs.getString("type"),
               });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
          
        clear();
    }
    
    private void clear(){
        jTF_nama.setText("");
        jTF_username.setText("");
        jPF_password.setText("");
    }
    
    private void create(){
        try {
 
            if( !jTF_nama.getText().isEmpty() && !jTF_username.getText().isEmpty() && !jPF_password.getText().isEmpty()){
                
                sql = "INSERT INTO user (nama, username, password, type) VALUES('" + jTF_nama.getText() + "', '" + 
                        jTF_username.getText() + "', '" + jPF_password.getText() + "', '" + jCB_type.getSelectedItem().toString()+ "');";

                stat.executeUpdate(sql);
                 JOptionPane.showMessageDialog(this, "User Berhasil ditambahkan");   
                 
            }else{
                JOptionPane.showMessageDialog(this, "Data User Masih ada yang Kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error input data" + e);
             
        }
        
        loadTabel();
        clear();
    }
    
    private void delete(){
        try {
            String id = String.valueOf(jT_user.getValueAt(jT_user.getSelectedRow(),1));
                if (JOptionPane.showConfirmDialog(this, "Yakin menghapus data", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                sql = "DELETE FROM user WHERE username='" + id + "'";
                stat.executeUpdate(sql);
            }else{
                return;
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadTabel();
        clear();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_create;
    private javax.swing.JButton jB_delete;
    private javax.swing.JButton jB_edit;
    private javax.swing.JButton jB_refresh;
    private javax.swing.JButton jB_search;
    private javax.swing.JComboBox<String> jCB_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPF_password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_nama;
    private javax.swing.JTextField jTF_search;
    private javax.swing.JTextField jTF_username;
    private javax.swing.JTable jT_user;
    // End of variables declaration//GEN-END:variables
}
