/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg9typical_cafe;

/**
 *
 * @author wolfie
 */
public class Form_MenuAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_MenuAdmin
     */
    public Form_MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_addUser = new javax.swing.JButton();
        jB_dashboard = new javax.swing.JButton();
        jB_inventory = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_addUser.setText("ADD USER");
        jB_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addUserActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 250, 120));

        jB_dashboard.setText("DASHBOARD");
        jB_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(jB_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 250, 120));

        jB_inventory.setText("INVENTORY");
        jB_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_inventoryActionPerformed(evt);
            }
        });
        getContentPane().add(jB_inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 250, 120));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_dashboardActionPerformed
        // TODO add your handling code here:
        Form_DashboardAdmin fda = new Form_DashboardAdmin();
        Home.jDesktopPane.removeAll();
        Home.jDesktopPane.repaint();
        fda.setVisible(true);
        Home.jDesktopPane.add(fda);
    }//GEN-LAST:event_jB_dashboardActionPerformed

    private void jB_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_inventoryActionPerformed
        // TODO add your handling code here:
        Form_InventoryAdmin fia = new Form_InventoryAdmin();
        Home.jDesktopPane.removeAll();
        Home.jDesktopPane.repaint();
        fia.setVisible(true);
        Home.jDesktopPane.add(fia);
    }//GEN-LAST:event_jB_inventoryActionPerformed

    private void jB_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addUserActionPerformed
        // TODO add your handling code here:
        Form_AddUser fau = new Form_AddUser();
        Home.jDesktopPane.removeAll();
        Home.jDesktopPane.repaint();
        fau.setVisible(true);
        Home.jDesktopPane.add(fau);
    }//GEN-LAST:event_jB_addUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_addUser;
    private javax.swing.JButton jB_dashboard;
    private javax.swing.JButton jB_inventory;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
