/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg9typical_cafe;

import Koneksi.Koneksi;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author wolfie
 */
public class Form_Login extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    String id_user;
    String hak;
    public Form_Login() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jB_login = new javax.swing.JButton();
        jTF_userName = new javax.swing.JTextField();
        jPF_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 300, 300));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 141, 57));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_login.setBackground(new java.awt.Color(51, 204, 0));
        jB_login.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jB_login.setForeground(new java.awt.Color(255, 255, 255));
        jB_login.setText("Login");
        jB_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_loginActionPerformed(evt);
            }
        });
        jPanel1.add(jB_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 180, 120, 50));

        jTF_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_userNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTF_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 60));

        jPF_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPF_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(jPF_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 310, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_userNameActionPerformed

    private void jB_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_loginActionPerformed
        // TODO add your handling code here:
       try {
            sql = "SELECT * FROM user WHERE username='"+jTF_userName.getText()+"' AND password='"+jPF_password.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                setIdUser(rs.getString("id_user"));

                hak = rs.getString("type");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       if (id_user != null) {
            
            this.dispose();
            if (hak.equals("Admin")) {
                JOptionPane.showMessageDialog(this, "Login Berhasil");
                System.out.println("Login Sebagai Admin");
                Home h = new Home();
                h.setVisible(true);
                h.admin();
            } else {
                JOptionPane.showMessageDialog(this, "Login Berhasil");
                System.out.println("Login Sebagai Kasir");
                Home h = new Home(getIdUser());
                h.setVisible(true);
                h.kasir();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Login Gagal, Coba Lagi!");
        }
    }//GEN-LAST:event_jB_loginActionPerformed

    private void jPF_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPF_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPF_passwordActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/assets/logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }
    
    private void setIdUser(String id_user){
        this.id_user = id_user;
    }
    
    public String getIdUser(){
        return id_user;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPF_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_userName;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
