/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg9typical_cafe;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author wolfie
 */

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Form_Home
     */
    private static String id_user;
    
    public Home(String id_user){
        this.id_user = id_user;
        initComponents();
        jB_Menu.setVisible(false);
        jB_confirmOrder.setVisible(false);
        jB_home.setVisible(false);
        jB_payment.setVisible(false);
        jB_MenuAdmin.setVisible(false);
        jB_homeAdmin.setVisible(false);
        
    }
    
    public Home() {
        initComponents();
        jB_Menu.setVisible(false);
        jB_confirmOrder.setVisible(false);
        jB_home.setVisible(false);
        jB_payment.setVisible(false);
        jB_MenuAdmin.setVisible(false);
        jB_homeAdmin.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane = new javax.swing.JDesktopPane();
        jB_MenuAdmin = new javax.swing.JButton();
        jB_homeAdmin = new javax.swing.JButton();
        jB_home = new javax.swing.JButton();
        jB_payment = new javax.swing.JButton();
        jB_Menu = new javax.swing.JButton();
        jB_confirmOrder = new javax.swing.JButton();
        jB_logOut = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1028, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane.setMinimumSize(new java.awt.Dimension(1028, 564));
        getContentPane().add(jDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 1280, 590));

        jB_MenuAdmin.setText("Menu");
        jB_MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MenuAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jB_MenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 120, 60));

        jB_homeAdmin.setText("Home");
        jB_homeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_homeAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jB_homeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 120, 60));

        jB_home.setText("Home");
        jB_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jB_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 120, 60));

        jB_payment.setText("Payment");
        jB_payment.setFocusPainted(false);
        getContentPane().add(jB_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 120, 60));

        jB_Menu.setText("Menu");
        jB_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 120, 60));

        jB_confirmOrder.setText("Confirm Order");
        jB_confirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_confirmOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jB_confirmOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 120, 60));

        jB_logOut.setBackground(new java.awt.Color(255, 102, 102));
        jB_logOut.setForeground(new java.awt.Color(255, 255, 255));
        jB_logOut.setText("LOG OUT");
        jB_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logOutActionPerformed(evt);
            }
        });
        getContentPane().add(jB_logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_homeActionPerformed
        // TODO add your handling code here:
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        Form_Home fh = new Form_Home();
        fh.setVisible(true);
        jDesktopPane.add(fh);
    }//GEN-LAST:event_jB_homeActionPerformed

    private void jB_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MenuActionPerformed
        // TODO add your handling code here:

            jDesktopPane.removeAll();
            jDesktopPane.repaint();
            Form_Menu fm = new Form_Menu();
            fm.setVisible(true);
            jDesktopPane.add(fm);
    }//GEN-LAST:event_jB_MenuActionPerformed

    private void jB_confirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_confirmOrderActionPerformed
        
    }//GEN-LAST:event_jB_confirmOrderActionPerformed

    private void jB_homeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_homeAdminActionPerformed
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        Form_Home fh = new Form_Home();
        fh.setVisible(true);
        jDesktopPane.add(fh);
    }//GEN-LAST:event_jB_homeAdminActionPerformed

    private void jB_MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MenuAdminActionPerformed
        // TODO add your handling code here:
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        Form_MenuAdmin fm = new Form_MenuAdmin();
        fm.setVisible(true);
        jDesktopPane.add(fm);
    }//GEN-LAST:event_jB_MenuAdminActionPerformed

    private void jB_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logOutActionPerformed

        Form_Login fl = new Form_Login();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jB_logOutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/assets/logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    public void admin () {
        jB_MenuAdmin.setVisible(true);
        jB_homeAdmin.setVisible(true);
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        Form_Home fh = new Form_Home();
        fh.admin();
        fh.setVisible(true);
        jDesktopPane.add(fh);
    }
    
    public void kasir() {
        jB_Menu.setVisible(true);
        jB_confirmOrder.setVisible(true);
        jB_home.setVisible(true);
        jB_payment.setVisible(true);
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        Form_Home fh = new Form_Home();
        fh.kasir();
        fh.setVisible(true);
        jDesktopPane.add(fh);
    }
    
    
    
    public static String getIdUser(){
        return id_user;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Menu;
    private javax.swing.JButton jB_MenuAdmin;
    private javax.swing.JButton jB_confirmOrder;
    private javax.swing.JButton jB_home;
    private javax.swing.JButton jB_homeAdmin;
    private javax.swing.JButton jB_logOut;
    private javax.swing.JButton jB_payment;
    public static javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
